/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RemarketingRouteImport } from './routes/remarketing'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as FluxosRouteImport } from './routes/fluxos'
import { Route as DisparosRouteImport } from './routes/disparos'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWhiteLabelRouteImport } from './routes/admin.white-label'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminSistemaRouteImport } from './routes/admin.sistema'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminFaturamentoRouteImport } from './routes/admin.faturamento'

const RemarketingRoute = RemarketingRouteImport.update({
  id: '/remarketing',
  path: '/remarketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxosRoute = FluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparosRoute = DisparosRouteImport.update({
  id: '/disparos',
  path: '/disparos',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhiteLabelRoute = AdminWhiteLabelRouteImport.update({
  id: '/white-label',
  path: '/white-label',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSistemaRoute = AdminSistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaturamentoRoute = AdminFaturamentoRouteImport.update({
  id: '/faturamento',
  path: '/faturamento',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendamento': typeof AgendamentoRoute
  '/agentes': typeof AgentesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/cursos': typeof CursosRoute
  '/disparos': typeof DisparosRoute
  '/fluxos': typeof FluxosRoute
  '/kanban': typeof KanbanRoute
  '/mensagens': typeof MensagensRoute
  '/pagamentos': typeof PagamentosRoute
  '/remarketing': typeof RemarketingRoute
  '/admin/faturamento': typeof AdminFaturamentoRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/sistema': typeof AdminSistemaRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/white-label': typeof AdminWhiteLabelRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/agentes': typeof AgentesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/cursos': typeof CursosRoute
  '/disparos': typeof DisparosRoute
  '/fluxos': typeof FluxosRoute
  '/kanban': typeof KanbanRoute
  '/mensagens': typeof MensagensRoute
  '/pagamentos': typeof PagamentosRoute
  '/remarketing': typeof RemarketingRoute
  '/admin/faturamento': typeof AdminFaturamentoRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/sistema': typeof AdminSistemaRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/white-label': typeof AdminWhiteLabelRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendamento': typeof AgendamentoRoute
  '/agentes': typeof AgentesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/cursos': typeof CursosRoute
  '/disparos': typeof DisparosRoute
  '/fluxos': typeof FluxosRoute
  '/kanban': typeof KanbanRoute
  '/mensagens': typeof MensagensRoute
  '/pagamentos': typeof PagamentosRoute
  '/remarketing': typeof RemarketingRoute
  '/admin/faturamento': typeof AdminFaturamentoRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/sistema': typeof AdminSistemaRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/white-label': typeof AdminWhiteLabelRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendamento'
    | '/agentes'
    | '/configuracoes'
    | '/contatos'
    | '/cursos'
    | '/disparos'
    | '/fluxos'
    | '/kanban'
    | '/mensagens'
    | '/pagamentos'
    | '/remarketing'
    | '/admin/faturamento'
    | '/admin/planos'
    | '/admin/sistema'
    | '/admin/suporte'
    | '/admin/tenants'
    | '/admin/usuarios'
    | '/admin/white-label'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento'
    | '/agentes'
    | '/configuracoes'
    | '/contatos'
    | '/cursos'
    | '/disparos'
    | '/fluxos'
    | '/kanban'
    | '/mensagens'
    | '/pagamentos'
    | '/remarketing'
    | '/admin/faturamento'
    | '/admin/planos'
    | '/admin/sistema'
    | '/admin/suporte'
    | '/admin/tenants'
    | '/admin/usuarios'
    | '/admin/white-label'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendamento'
    | '/agentes'
    | '/configuracoes'
    | '/contatos'
    | '/cursos'
    | '/disparos'
    | '/fluxos'
    | '/kanban'
    | '/mensagens'
    | '/pagamentos'
    | '/remarketing'
    | '/admin/faturamento'
    | '/admin/planos'
    | '/admin/sistema'
    | '/admin/suporte'
    | '/admin/tenants'
    | '/admin/usuarios'
    | '/admin/white-label'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendamentoRoute: typeof AgendamentoRoute
  AgentesRoute: typeof AgentesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContatosRoute: typeof ContatosRoute
  CursosRoute: typeof CursosRoute
  DisparosRoute: typeof DisparosRoute
  FluxosRoute: typeof FluxosRoute
  KanbanRoute: typeof KanbanRoute
  MensagensRoute: typeof MensagensRoute
  PagamentosRoute: typeof PagamentosRoute
  RemarketingRoute: typeof RemarketingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/remarketing': {
      id: '/remarketing'
      path: '/remarketing'
      fullPath: '/remarketing'
      preLoaderRoute: typeof RemarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxos': {
      id: '/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof FluxosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparos': {
      id: '/disparos'
      path: '/disparos'
      fullPath: '/disparos'
      preLoaderRoute: typeof DisparosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/white-label': {
      id: '/admin/white-label'
      path: '/white-label'
      fullPath: '/admin/white-label'
      preLoaderRoute: typeof AdminWhiteLabelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sistema': {
      id: '/admin/sistema'
      path: '/sistema'
      fullPath: '/admin/sistema'
      preLoaderRoute: typeof AdminSistemaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faturamento': {
      id: '/admin/faturamento'
      path: '/faturamento'
      fullPath: '/admin/faturamento'
      preLoaderRoute: typeof AdminFaturamentoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFaturamentoRoute: typeof AdminFaturamentoRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminSistemaRoute: typeof AdminSistemaRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminWhiteLabelRoute: typeof AdminWhiteLabelRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFaturamentoRoute: AdminFaturamentoRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminSistemaRoute: AdminSistemaRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminWhiteLabelRoute: AdminWhiteLabelRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendamentoRoute: AgendamentoRoute,
  AgentesRoute: AgentesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContatosRoute: ContatosRoute,
  CursosRoute: CursosRoute,
  DisparosRoute: DisparosRoute,
  FluxosRoute: FluxosRoute,
  KanbanRoute: KanbanRoute,
  MensagensRoute: MensagensRoute,
  PagamentosRoute: PagamentosRoute,
  RemarketingRoute: RemarketingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
