/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RemarketingRouteImport } from './routes/remarketing'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as FluxosRouteImport } from './routes/fluxos'
import { Route as DisparosRouteImport } from './routes/disparos'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as IndexRouteImport } from './routes/index'

const RemarketingRoute = RemarketingRouteImport.update({
  id: '/remarketing',
  path: '/remarketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxosRoute = FluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparosRoute = DisparosRouteImport.update({
  id: '/disparos',
  path: '/disparos',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/cursos': typeof CursosRoute
  '/disparos': typeof DisparosRoute
  '/fluxos': typeof FluxosRoute
  '/kanban': typeof KanbanRoute
  '/mensagens': typeof MensagensRoute
  '/remarketing': typeof RemarketingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/cursos': typeof CursosRoute
  '/disparos': typeof DisparosRoute
  '/fluxos': typeof FluxosRoute
  '/kanban': typeof KanbanRoute
  '/mensagens': typeof MensagensRoute
  '/remarketing': typeof RemarketingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/cursos': typeof CursosRoute
  '/disparos': typeof DisparosRoute
  '/fluxos': typeof FluxosRoute
  '/kanban': typeof KanbanRoute
  '/mensagens': typeof MensagensRoute
  '/remarketing': typeof RemarketingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes'
    | '/configuracoes'
    | '/contatos'
    | '/cursos'
    | '/disparos'
    | '/fluxos'
    | '/kanban'
    | '/mensagens'
    | '/remarketing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes'
    | '/configuracoes'
    | '/contatos'
    | '/cursos'
    | '/disparos'
    | '/fluxos'
    | '/kanban'
    | '/mensagens'
    | '/remarketing'
  id:
    | '__root__'
    | '/'
    | '/agentes'
    | '/configuracoes'
    | '/contatos'
    | '/cursos'
    | '/disparos'
    | '/fluxos'
    | '/kanban'
    | '/mensagens'
    | '/remarketing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesRoute: typeof AgentesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContatosRoute: typeof ContatosRoute
  CursosRoute: typeof CursosRoute
  DisparosRoute: typeof DisparosRoute
  FluxosRoute: typeof FluxosRoute
  KanbanRoute: typeof KanbanRoute
  MensagensRoute: typeof MensagensRoute
  RemarketingRoute: typeof RemarketingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/remarketing': {
      id: '/remarketing'
      path: '/remarketing'
      fullPath: '/remarketing'
      preLoaderRoute: typeof RemarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxos': {
      id: '/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof FluxosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparos': {
      id: '/disparos'
      path: '/disparos'
      fullPath: '/disparos'
      preLoaderRoute: typeof DisparosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesRoute: AgentesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContatosRoute: ContatosRoute,
  CursosRoute: CursosRoute,
  DisparosRoute: DisparosRoute,
  FluxosRoute: FluxosRoute,
  KanbanRoute: KanbanRoute,
  MensagensRoute: MensagensRoute,
  RemarketingRoute: RemarketingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
