/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ExclusaoDeDadosRouteImport } from './routes/exclusao-de-dados'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedRemarketingRouteImport } from './routes/_authenticated.remarketing'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated.pagamentos'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated.mensagens'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated.kanban'
import { Route as AuthenticatedFluxosRouteImport } from './routes/_authenticated.fluxos'
import { Route as AuthenticatedDisparosRouteImport } from './routes/_authenticated.disparos'
import { Route as AuthenticatedCursosRouteImport } from './routes/_authenticated.cursos'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated.contatos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedAgentesRouteImport } from './routes/_authenticated.agentes'
import { Route as AuthenticatedAgendamentoRouteImport } from './routes/_authenticated.agendamento'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminWhiteLabelRouteImport } from './routes/_authenticated.admin.white-label'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated.admin.usuarios'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated.admin.tenants'
import { Route as AuthenticatedAdminSuporteRouteImport } from './routes/_authenticated.admin.suporte'
import { Route as AuthenticatedAdminSistemaRouteImport } from './routes/_authenticated.admin.sistema'
import { Route as AuthenticatedAdminPlanosRouteImport } from './routes/_authenticated.admin.planos'
import { Route as AuthenticatedAdminFaturamentoRouteImport } from './routes/_authenticated.admin.faturamento'
import { Route as AuthenticatedAdminDominiosRouteImport } from './routes/_authenticated.admin.dominios'
import { Route as AuthenticatedAdminConfiguracaoRouteImport } from './routes/_authenticated.admin.configuracao'
import { Route as AuthenticatedAdminCalendarioRouteImport } from './routes/_authenticated.admin.calendario'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api.public.whatsapp.webhook'
import { Route as ApiPublicMetaDeauthorizeRouteImport } from './routes/api.public.meta.deauthorize'
import { Route as ApiPublicMetaDataDeletionRouteImport } from './routes/api.public.meta.data-deletion'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaoDeDadosRoute = ExclusaoDeDadosRouteImport.update({
  id: '/exclusao-de-dados',
  path: '/exclusao-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRemarketingRoute =
  AuthenticatedRemarketingRouteImport.update({
    id: '/remarketing',
    path: '/remarketing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFluxosRoute = AuthenticatedFluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDisparosRoute = AuthenticatedDisparosRouteImport.update({
  id: '/disparos',
  path: '/disparos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCursosRoute = AuthenticatedCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentesRoute = AuthenticatedAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendamentoRoute =
  AuthenticatedAgendamentoRouteImport.update({
    id: '/agendamento',
    path: '/agendamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWhiteLabelRoute =
  AuthenticatedAdminWhiteLabelRouteImport.update({
    id: '/white-label',
    path: '/white-label',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuporteRoute =
  AuthenticatedAdminSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSistemaRoute =
  AuthenticatedAdminSistemaRouteImport.update({
    id: '/sistema',
    path: '/sistema',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlanosRoute =
  AuthenticatedAdminPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFaturamentoRoute =
  AuthenticatedAdminFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDominiosRoute =
  AuthenticatedAdminDominiosRouteImport.update({
    id: '/dominios',
    path: '/dominios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracaoRoute =
  AuthenticatedAdminConfiguracaoRouteImport.update({
    id: '/configuracao',
    path: '/configuracao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarioRoute =
  AuthenticatedAdminCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaDeauthorizeRoute =
  ApiPublicMetaDeauthorizeRouteImport.update({
    id: '/api/public/meta/deauthorize',
    path: '/api/public/meta/deauthorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaDataDeletionRoute =
  ApiPublicMetaDataDeletionRouteImport.update({
    id: '/api/public/meta/data-deletion',
    path: '/api/public/meta/data-deletion',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agendamento': typeof AuthenticatedAgendamentoRoute
  '/agentes': typeof AuthenticatedAgentesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/cursos': typeof AuthenticatedCursosRoute
  '/disparos': typeof AuthenticatedDisparosRoute
  '/fluxos': typeof AuthenticatedFluxosRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/remarketing': typeof AuthenticatedRemarketingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/configuracao': typeof AuthenticatedAdminConfiguracaoRoute
  '/admin/dominios': typeof AuthenticatedAdminDominiosRoute
  '/admin/faturamento': typeof AuthenticatedAdminFaturamentoRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/sistema': typeof AuthenticatedAdminSistemaRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/white-label': typeof AuthenticatedAdminWhiteLabelRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/meta/data-deletion': typeof ApiPublicMetaDataDeletionRoute
  '/api/public/meta/deauthorize': typeof ApiPublicMetaDeauthorizeRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/agendamento': typeof AuthenticatedAgendamentoRoute
  '/agentes': typeof AuthenticatedAgentesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/cursos': typeof AuthenticatedCursosRoute
  '/disparos': typeof AuthenticatedDisparosRoute
  '/fluxos': typeof AuthenticatedFluxosRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/remarketing': typeof AuthenticatedRemarketingRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/configuracao': typeof AuthenticatedAdminConfiguracaoRoute
  '/admin/dominios': typeof AuthenticatedAdminDominiosRoute
  '/admin/faturamento': typeof AuthenticatedAdminFaturamentoRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/sistema': typeof AuthenticatedAdminSistemaRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/white-label': typeof AuthenticatedAdminWhiteLabelRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/meta/data-deletion': typeof ApiPublicMetaDataDeletionRoute
  '/api/public/meta/deauthorize': typeof ApiPublicMetaDeauthorizeRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agendamento': typeof AuthenticatedAgendamentoRoute
  '/_authenticated/agentes': typeof AuthenticatedAgentesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contatos': typeof AuthenticatedContatosRoute
  '/_authenticated/cursos': typeof AuthenticatedCursosRoute
  '/_authenticated/disparos': typeof AuthenticatedDisparosRoute
  '/_authenticated/fluxos': typeof AuthenticatedFluxosRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/remarketing': typeof AuthenticatedRemarketingRoute
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/_authenticated/admin/configuracao': typeof AuthenticatedAdminConfiguracaoRoute
  '/_authenticated/admin/dominios': typeof AuthenticatedAdminDominiosRoute
  '/_authenticated/admin/faturamento': typeof AuthenticatedAdminFaturamentoRoute
  '/_authenticated/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/_authenticated/admin/sistema': typeof AuthenticatedAdminSistemaRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/white-label': typeof AuthenticatedAdminWhiteLabelRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/meta/data-deletion': typeof ApiPublicMetaDataDeletionRoute
  '/api/public/meta/deauthorize': typeof ApiPublicMetaDeauthorizeRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/exclusao-de-dados'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/agendamento'
    | '/agentes'
    | '/configuracoes'
    | '/contatos'
    | '/cursos'
    | '/disparos'
    | '/fluxos'
    | '/kanban'
    | '/mensagens'
    | '/pagamentos'
    | '/remarketing'
    | '/admin/login'
    | '/admin/calendario'
    | '/admin/configuracao'
    | '/admin/dominios'
    | '/admin/faturamento'
    | '/admin/planos'
    | '/admin/sistema'
    | '/admin/suporte'
    | '/admin/tenants'
    | '/admin/usuarios'
    | '/admin/white-label'
    | '/admin/'
    | '/api/public/meta/data-deletion'
    | '/api/public/meta/deauthorize'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/exclusao-de-dados'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/agendamento'
    | '/agentes'
    | '/configuracoes'
    | '/contatos'
    | '/cursos'
    | '/disparos'
    | '/fluxos'
    | '/kanban'
    | '/mensagens'
    | '/pagamentos'
    | '/remarketing'
    | '/admin/login'
    | '/'
    | '/admin/calendario'
    | '/admin/configuracao'
    | '/admin/dominios'
    | '/admin/faturamento'
    | '/admin/planos'
    | '/admin/sistema'
    | '/admin/suporte'
    | '/admin/tenants'
    | '/admin/usuarios'
    | '/admin/white-label'
    | '/admin'
    | '/api/public/meta/data-deletion'
    | '/api/public/meta/deauthorize'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/exclusao-de-dados'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/agendamento'
    | '/_authenticated/agentes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contatos'
    | '/_authenticated/cursos'
    | '/_authenticated/disparos'
    | '/_authenticated/fluxos'
    | '/_authenticated/kanban'
    | '/_authenticated/mensagens'
    | '/_authenticated/pagamentos'
    | '/_authenticated/remarketing'
    | '/admin/login'
    | '/_authenticated/'
    | '/_authenticated/admin/calendario'
    | '/_authenticated/admin/configuracao'
    | '/_authenticated/admin/dominios'
    | '/_authenticated/admin/faturamento'
    | '/_authenticated/admin/planos'
    | '/_authenticated/admin/sistema'
    | '/_authenticated/admin/suporte'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/white-label'
    | '/_authenticated/admin/'
    | '/api/public/meta/data-deletion'
    | '/api/public/meta/deauthorize'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExclusaoDeDadosRoute: typeof ExclusaoDeDadosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPublicMetaDataDeletionRoute: typeof ApiPublicMetaDataDeletionRoute
  ApiPublicMetaDeauthorizeRoute: typeof ApiPublicMetaDeauthorizeRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusao-de-dados': {
      id: '/exclusao-de-dados'
      path: '/exclusao-de-dados'
      fullPath: '/exclusao-de-dados'
      preLoaderRoute: typeof ExclusaoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/remarketing': {
      id: '/_authenticated/remarketing'
      path: '/remarketing'
      fullPath: '/remarketing'
      preLoaderRoute: typeof AuthenticatedRemarketingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fluxos': {
      id: '/_authenticated/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof AuthenticatedFluxosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disparos': {
      id: '/_authenticated/disparos'
      path: '/disparos'
      fullPath: '/disparos'
      preLoaderRoute: typeof AuthenticatedDisparosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cursos': {
      id: '/_authenticated/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof AuthenticatedCursosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agentes': {
      id: '/_authenticated/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AuthenticatedAgentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agendamento': {
      id: '/_authenticated/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AuthenticatedAgendamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/white-label': {
      id: '/_authenticated/admin/white-label'
      path: '/white-label'
      fullPath: '/admin/white-label'
      preLoaderRoute: typeof AuthenticatedAdminWhiteLabelRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sistema': {
      id: '/_authenticated/admin/sistema'
      path: '/sistema'
      fullPath: '/admin/sistema'
      preLoaderRoute: typeof AuthenticatedAdminSistemaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/planos': {
      id: '/_authenticated/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AuthenticatedAdminPlanosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faturamento': {
      id: '/_authenticated/admin/faturamento'
      path: '/faturamento'
      fullPath: '/admin/faturamento'
      preLoaderRoute: typeof AuthenticatedAdminFaturamentoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dominios': {
      id: '/_authenticated/admin/dominios'
      path: '/dominios'
      fullPath: '/admin/dominios'
      preLoaderRoute: typeof AuthenticatedAdminDominiosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracao': {
      id: '/_authenticated/admin/configuracao'
      path: '/configuracao'
      fullPath: '/admin/configuracao'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendario': {
      id: '/_authenticated/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AuthenticatedAdminCalendarioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/deauthorize': {
      id: '/api/public/meta/deauthorize'
      path: '/api/public/meta/deauthorize'
      fullPath: '/api/public/meta/deauthorize'
      preLoaderRoute: typeof ApiPublicMetaDeauthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/data-deletion': {
      id: '/api/public/meta/data-deletion'
      path: '/api/public/meta/data-deletion'
      fullPath: '/api/public/meta/data-deletion'
      preLoaderRoute: typeof ApiPublicMetaDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCalendarioRoute: typeof AuthenticatedAdminCalendarioRoute
  AuthenticatedAdminConfiguracaoRoute: typeof AuthenticatedAdminConfiguracaoRoute
  AuthenticatedAdminDominiosRoute: typeof AuthenticatedAdminDominiosRoute
  AuthenticatedAdminFaturamentoRoute: typeof AuthenticatedAdminFaturamentoRoute
  AuthenticatedAdminPlanosRoute: typeof AuthenticatedAdminPlanosRoute
  AuthenticatedAdminSistemaRoute: typeof AuthenticatedAdminSistemaRoute
  AuthenticatedAdminSuporteRoute: typeof AuthenticatedAdminSuporteRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminWhiteLabelRoute: typeof AuthenticatedAdminWhiteLabelRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCalendarioRoute: AuthenticatedAdminCalendarioRoute,
  AuthenticatedAdminConfiguracaoRoute: AuthenticatedAdminConfiguracaoRoute,
  AuthenticatedAdminDominiosRoute: AuthenticatedAdminDominiosRoute,
  AuthenticatedAdminFaturamentoRoute: AuthenticatedAdminFaturamentoRoute,
  AuthenticatedAdminPlanosRoute: AuthenticatedAdminPlanosRoute,
  AuthenticatedAdminSistemaRoute: AuthenticatedAdminSistemaRoute,
  AuthenticatedAdminSuporteRoute: AuthenticatedAdminSuporteRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminWhiteLabelRoute: AuthenticatedAdminWhiteLabelRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgendamentoRoute: typeof AuthenticatedAgendamentoRoute
  AuthenticatedAgentesRoute: typeof AuthenticatedAgentesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRoute
  AuthenticatedCursosRoute: typeof AuthenticatedCursosRoute
  AuthenticatedDisparosRoute: typeof AuthenticatedDisparosRoute
  AuthenticatedFluxosRoute: typeof AuthenticatedFluxosRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedRemarketingRoute: typeof AuthenticatedRemarketingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgendamentoRoute: AuthenticatedAgendamentoRoute,
  AuthenticatedAgentesRoute: AuthenticatedAgentesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContatosRoute: AuthenticatedContatosRoute,
  AuthenticatedCursosRoute: AuthenticatedCursosRoute,
  AuthenticatedDisparosRoute: AuthenticatedDisparosRoute,
  AuthenticatedFluxosRoute: AuthenticatedFluxosRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedRemarketingRoute: AuthenticatedRemarketingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ExclusaoDeDadosRoute: ExclusaoDeDadosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiPublicMetaDataDeletionRoute: ApiPublicMetaDataDeletionRoute,
  ApiPublicMetaDeauthorizeRoute: ApiPublicMetaDeauthorizeRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
